linters:
  enable:
    - dupl
    - gocognit
    - goconst
    - gocyclo
    - godot
    - gofmt
    - gosec
    - revive
    - typecheck
    - unparam
linters-settings:
  gosec:
    excludes:
      - G204
