project_name: git-matsuri
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/MatsuriJapon/git-matsuri/cmd.currentVersion={{.Version}}
      - -X github.com/MatsuriJapon/git-matsuri/cmd.commit={{.Commit}}
      - -X github.com/MatsuriJapon/git-matsuri/cmd.date={{.Date}}
      - -X github.com/MatsuriJapon/git-matsuri/cmd.builtBy=goreleaser
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
