version: 2.1

executors:
  go-executor:
    docker:
      - image: golang:latest
    working_directory: /work


jobs:
  lint:
    executor: go-executor
    steps:
    - checkout
    - run: make lint
  build:
    executor: go-executor
    steps:
    - checkout
    - run: make build
  release:
    executor: go-executor
    steps:
    - attach_workspace:
      at: /work/artifacts
    - run: go get github.com/tcnksm/ghr
    - run: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./artifacts/

workflows:
  version: 2
  main:
    jobs:
      - lint
      - build:
          filters:
            branches:
              only: master
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/