version: 2
jobs:
  build:
    docker:
    - image: golang:latest
    working_directory: /work
    steps:
    - checkout
    - run: make lint
  publish-git-release:
    docker:
    - image: golang:latest
    working_directory: /work
    steps:
    - checkout
    - run: go get github.com/tcnksm/ghr
    - run: make build
    - run: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./artifacts/

workflows:
  version: 2
  main:
    jobs:
      - build
      - publish-git-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/